version: 2.1
orbs:
  codecov: codecov/codecov@1.1.1
jobs:
  test:
    environment:
      CODECOV_TOKEN: 08a98f72-f099-432a-a6b5-49c1f134fe90
    docker:
      - image: cimg/node:20.12.2
    working_directory: ~/repo
    resource_class: large
    steps:
      - checkout
      - run:
          name: set GIT name and email
          command: |
            git config --global -l
            git config --global user.email "$GIT_COMMITTER_EMAIL"
            git config --global user.name "$GIT_COMMITTER_NAME"
            git config --global -l
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - strapi-plugin-reactions-v2-{{ checksum "yarn.lock" }}
            - strapi-plugin-reactions-
      - run:
          name: Echo versions
          command: |
            node --version
            yarn --version
      - run:
          name: Configure NPM
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Install
          command: |
            yarn install
      - run:
          name: Test
          command: |
            yarn test:unit:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/
      - store_test_results:
          path: ./reports/
      - codecov/upload:
          flags: unittest
          file:
      - save_cache:
          paths:
            - ./node_modules
          key: strapi-plugin-reactions-v2-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ~/repo
          paths: .
  deploy:
    environment:
      CODECOV_TOKEN: 08a98f72-f099-432a-a6b5-49c1f134fe90
    docker:
      - image: cimg/node:20.12.2
    working_directory: ~/repo
    resource_class: large
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Configure NPM
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Build
          command: |
            yarn build
      - run:
          name: Publish package
          command: npm publish --tag beta

workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/